name: CI

on: [push]

jobs:
  golangci-lint:
     name: runner / golangci-lint
     runs-on: ubuntu-latest
     steps:
     - name: Check out code into the Go module directory
       uses: actions/checkout@v1
     - name: golangci-lint
       uses: reviewdog/action-golangci-lint@v1
       # uses: docker://reviewdog/action-golangci-lint:v1 # pre-build docker image
       with:
          github_token: ${{ secrets.github_token }}
    
     - uses: reviewdog/action-golangci-lint@v1.1.3
     - name: Run golangci-lint with reviewdog
       run: echo Hello Bodja!
