name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: reviewdog/action-golangci-lint@v1.1.3
    - name: Run golangci-lint with reviewdog
      run: echo Hello Bodja!
